/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import dbConnect.PasswordHasher;
import dbConnect.dbConnector;
import dbconnect.Session;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Windows 10
 */
public class ChangePassword extends javax.swing.JFrame {

    /**
     * Creates new form ChangePassword
     */
    public ChangePassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Back = new javax.swing.JButton();
        name = new javax.swing.JLabel();
        LastName = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        newPassword = new javax.swing.JPasswordField();
        Save = new javax.swing.JButton();
        Cpassword = new javax.swing.JPasswordField();
        oldPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHANGE PASSWORD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 50));

        Back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Back.setText("Back");
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackMouseClicked(evt);
            }
        });
        getContentPane().add(Back, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 120, 40));

        name.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Enter Old Pass :");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 120, 30));

        LastName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        LastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LastName.setText("Enter New Pass :");
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 120, 30));

        user.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        user.setText("Confirm Pass    :");
        getContentPane().add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 120, 30));

        jLabel7.setBackground(new java.awt.Color(102, 102, 255));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 120, 330));
        getContentPane().add(newPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 260, 30));

        Save.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 130, 40));
        getContentPane().add(Cpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 260, 30));
        getContentPane().add(oldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, 260, 30));

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 440, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        String passw = new String(newPassword.getPassword()).trim();
        String Cpassw = new String(Cpassword.getPassword()).trim();

        if(passw.isEmpty() || Cpassw.isEmpty() || oldPassword.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Fill all Boxes");
        }else if(passw.length() <= 7)
        {
            JOptionPane.showMessageDialog(null, "Password Must be Exactly 8 Characters Long");
        }else if(!passw.equals(Cpassw))
        {
            JOptionPane.showMessageDialog(null, "Password does not match");
        }else if(passw.equals(Cpassw))
        {
            try
            {
                dbConnector dbc = new dbConnector();
                Session sess = Session.getInstance();

                String query = "SELECT * FROM user WHERE i_id='"+ sess.getIid() +"'";
                ResultSet rs = dbc .getData(query);
                if(rs.next())
                {
                    String olddbPassword = rs.getString("i_password");
                    String oldhash = PasswordHasher.hashPassword(oldPassword.getText());

                    if(olddbPassword.equals(oldhash))
                    {

                        String npass = PasswordHasher.hashPassword(newPassword.getText());
                        dbc.updateData("UPDATE user SET i_password = '"+npass+"'WHERE i_id = '"+sess.getIid()+"'");
                       

                        JOptionPane.showMessageDialog(null, "Updated Succesfully");
                        UserDashboard ud = new UserDashboard();
                        ud.setVisible(true);
                        this.dispose();

                    }else
                    {
                        JOptionPane.showMessageDialog(null, "Old Password is Incorrect");
                    }
                }
            } catch(SQLException | NoSuchAlgorithmException ex)
            {
                System.out.println(""+ex);
            }
        }else
        {
            JOptionPane.showMessageDialog(null, "Unknown Error Occured");
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void BackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMouseClicked
       UserDashboard ud = new UserDashboard();
        ud.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back;
    private javax.swing.JPasswordField Cpassword;
    private javax.swing.JLabel LastName;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel name;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JPasswordField oldPassword;
    private javax.swing.JLabel user;
    // End of variables declaration//GEN-END:variables
}
